apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe
  template:
    metadata:
      labels:
        app: frappe
    spec:
      containers:
        - name: frappe
          image: frappe/bench:latest
          command: ["/bin/bash", "/workspace/init.sh"]
          env:
            - name: SHELL
              value: "/bin/bash"
          workingDir: /home/frappe
          ports:
            - containerPort: 8000
            - containerPort: 9000
          volumeMounts:
            - name: frappe-storage
              mountPath: /workspace
      volumes:
        - name: frappe-storage
          persistentVolumeClaim:
            claimName: frappe-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: frappe
spec:
  selector:
    app: frappe
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
