apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frappe-crm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/vkig2615/crm.git"
    targetRevision: develop
    path: "k8s"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
